### ISSUE TITLE
Embeds Don't Allow for Bullets/Formatting Directly Underneath Them

### ISSUE THREAD

**Issue by mgworldwide** [GnoxNahte/obsidian-auto-embed#13]
When you embed something in a list, press space after the link of the embed and try to include another bullet point below it, it doesn't work.

How to replicate:
1. Create a list
2. Paste a link to media
3. Embed it
4. Press space after the link
5. Try to write/use formatting

**Comment by GnoxNahte** [comment]
Hi thanks for the bug report, but I'm not sure what you meant as it looks fine to me. Maybe the spacing looks wrong but I have no idea how to fix it in Live preview mode... All the text shows up correctly though?

Here's how it looks for me in the different views. From left to right: Source mode, Live Preview, Reading Mode.
![image](https://github.com/user-attachments/assets/891bf810-c9f3-4964-b050-6432081994e2)

The markdown I used:
```
- ![](https://github.com/GnoxNahte/obsidian-auto-embed/issues/13) 
- other notes
```
Also for any future issues, it might be better if you can put the markdown you used so that I can copy and paste when I'm testing.

**Comment by mgworldwide** [comment]
Okay now it works, it was because I put a space after the closing bracket.
