### ISSUE TITLE
[BUG]: Embeds not rendering in bullet lists

### ISSUE THREAD

**Issue by Rikiub** [GnoxNahte/obsidian-auto-embed#6]
**Hello! It's me again.**
This is a little bug which only happens in **Live Preview** mode.

When I embed a link inside a bullet list, it doesn't embed, instead it shows an "generic image icon" and doesn't show the embed like the **Reading view**.

### Live preview
![RyBCwCHAFZ](https://github.com/user-attachments/assets/f0adb0b8-711e-484a-aee3-559e1cb62711)

### Reading view
![Obsidian_lxbG5o03o4](https://github.com/user-attachments/assets/f64cb9db-1a9a-4792-992c-1937e95f4242)

### Link used

https://www.tiktok.com/@zachking/video/6749520869598481669

**Comment by GnoxNahte** [comment]
It should be fixed on this release. There's a small problem - this bug might happen again in Live Preview (not from lists but maybe some other markdown). Please report it if it shows up again!

Sort of related but there's another bug where you need an extra space after each list (only in Live Preview). I've been trying to solve this for quite some time but I'm stuck. Just letting you know in case it affects you.
Here's an example image. Blue arrows are where the checkbox belongs to. If you don't have a new line, it'll look like the last checkbox.
<img width="556" alt="image" src="https://github.com/user-attachments/assets/cc3f542d-7c3e-4820-abce-e98a91aa8e52">

Here's the reason why the original bug might happen again if you are curious (though it's a bit technical and I'm not that good at explaining 😅):
The plugin searches for a type that Obsidian sets to the markdown. If you embed the link normally, the type is "string_url". But if you embed with lists, it'll be `list-1_string_url`. Indenting the list increases the list number (`list-2`, `list-3`, `list-4`, etc). 
The problem is I can't find any documentation on Obsidian or CodeMirror (what Obsidian uses in Live Preview). So I have no idea if there are other types. I can just search for "string_url" but then the plugin might try to embed something that it shouldn't which I think is worse.

Well anyway, just report if the problem comes up again! Thanks for the report as usual!

**Comment by Rikiub** [comment]
The fix works like a charm!

And yeah, the bug what you explain maybe should be in another issue?
For now, it doesn't affect me, but better safe than sorry.

**Comment by GnoxNahte** [comment]
Great!

Sure! I'll create a new issue with a better description when I'm free.
